#! /bin/bash

ISO="/home/pmy/Downloads/debian-9.1.0-amd64-netinst.iso"
MOUNT="/mnt/iso"
WORK="/var/tmp/debiso"
PASSWORD="foobar"

if [ ! "`whoami`" = "root" ]; then
	echo "run as root"
	exit
fi

if [ ! -d $MOUNT ]; then
	mkdir $MOUNT
fi

##### mount ISO image, copy to work area

mount -o loop,ro $ISO $MOUNT
rm -rf $WORK
mkdir -p $WORK
rsync -av $MOUNT/ $WORK
umount $MOUNT

##### set non-zero boot timeout to autostart install

sed -i -e 's/timeout 0$/timeout 50/' $WORK/isolinux/isolinux.cfg

##### edit initrd

#	patch preseed.cfg

m4 -DPASSWORD=$PASSWORD \
	preseed.cfg > $WORK/preseed.cfg

cp finalize $WORK/finalize
cp find_disk $WORK/find_disk

HERE=$PWD
cd $WORK

#	edit command initrd

INITRD="install.amd/initrd"
gunzip $INITRD.gz
echo preseed.cfg | cpio -H newc -o -A -F $INITRD
echo finalize | cpio -H newc -o -A -F $INITRD
echo find_disk | cpio -H newc -o -A -F $INITRD
gzip $INITRD

#	edit graphic initrd

INITRD="install.amd/gtk/initrd"
gunzip $INITRD.gz
echo preseed.cfg | cpio -H newc -o -A -F $INITRD
echo finalize | cpio -H newc -o -A -F $INITRD
echo find_disk | cpio -H newc -o -A -F $INITRD
gzip $INITRD

##### update checksum

rm preseed.cfg
rm finalize
rm find_disk
md5sum `find -follow -type f` > md5sum.txt

##### remaster ISO image

cd $HERE
BASE=`basename $ISO`
PRESEED="preseed-${BASE}"
genisoimage -r -J -b isolinux/isolinux.bin -c isolinux/boot.cat \
	-no-emul-boot -boot-load-size 4 -boot-info-table \
	-o ${PRESEED} $WORK
isohybrid $PRESEED
